# SpringBoot Web项目端口
server.port: 8071

# 项目应用名称
spring.application.name: nacos-helloworld

# 重要配置 配置 Nacos Server 注册中心的地址 IP:PORT
spring.cloud.nacos.discovery.server-addr: 127.0.0.1:8848

# 打开所有的端点
# management.endpoints.web.exposure.include: *