server:
  port: 9001
Spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 8.141.49.217:8848
management:
  endpoint:
    web:
      exposure:
        include: '*'